### ISSUE TITLE
[MINDEXER-30] IndexPublisher does not protect "read consistency" over published context

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-indexer#438]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** opened **[MINDEXER-30](https://issues.apache.org/jira/browse/MINDEXER-30?redirect=false)** and commented

IndexPublisher does not protect "read consistency" over published context.

This affects only contexts that are the new MergedIndexingContext. These -- newly introduced context types in 4.1.0 -- are simply "logical merged view" of other IndexingContexts. When some change -- and async commit -- happens in some of the member contexts, a Lucene exception is thrown preventing proper publishing of the context.

Typical top lines of these stack traces:

```
org.apache.lucene.store.AlreadyClosedException: this IndexReader is closed
at org.apache.lucene.index.IndexReader.ensureOpen(IndexReader.java:177)
at org.apache.lucene.index.SegmentReader.document(SegmentReader.java:942)
at org.apache.lucene.index.DirectoryReader.document(DirectoryReader.java:533)
at org.apache.lucene.index.MultiReader.document(MultiReader.java:251)
at org.apache.lucene.index.IndexReader.document(IndexReader.java:658)
at org.apache.maven.index.incremental.DefaultIncrementalHandler.getIndexChunk(DefaultIncrementalHandler.java:154)
at org.apache.maven.index.incremental.DefaultIncrementalHandler.getIncrementalUpdates(DefaultIncrementalHandler.java:65)
at org.apache.maven.index.packer.DefaultIndexPacker.packIndex(DefaultIndexPacker.java:117)
```

---

**Affects:** 4.1.0

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Fixed
