### ISSUE TITLE
[MINDEXER-164] IndexOutOfBoundsException during indexing of repositories files

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-indexer#518]
**[Fabian Windheuser](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER285178)** opened **[MINDEXER-164](https://issues.apache.org/jira/browse/MINDEXER-164?redirect=false)** and commented

This is similar to the issue filed in https://issues.apache.org/jira/browse/MINDEXER-144.

Starting with Maven 3.0.x, Maven creates "_*.repositories" file to record where the file was resolved from ([source|https://stackoverflow.com/questions/16866978/maven-cant-find-my-local-artifacts/16870552#16870552).] When the maven-indexer encounters such files, it errors with an IndexOutOfBoundsException.

 

Example stacktrace:

```java
Caused by: java.lang.IndexOutOfBoundsException: start 56, end 64, length 57
	at java.base/java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1794)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:675)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:217)
	at org.apache.maven.index.artifact.M2GavCalculator.getSnapshotGav(M2GavCalculator.java:188)
	at org.apache.maven.index.artifact.M2GavCalculator.pathToGav(M2GavCalculator.java:104)
	at org.apache.maven.index.DefaultArtifactContextProducer.getGavFromPath(DefaultArtifactContextProducer.java:160)
	at org.apache.maven.index.DefaultArtifactContextProducer.getArtifactContext(DefaultArtifactContextProducer.java:83)
	at org.apache.maven.index.DefaultScanner.processFile(DefaultScanner.java:109)
	at org.apache.maven.index.DefaultScanner.scanDirectory(DefaultScanner.java:99)
	at org.apache.maven.index.DefaultScanner.scanDirectory(DefaultScanner.java:91)
	at org.apache.maven.index.DefaultScanner.scanDirectory(DefaultScanner.java:91)
	at org.apache.maven.index.DefaultScanner.scanDirectory(DefaultScanner.java:91)
	at org.apache.maven.index.DefaultScanner.scanDirectory(DefaultScanner.java:91)
	at org.apache.maven.index.DefaultScanner.scanDirectory(DefaultScanner.java:91)
	at org.apache.maven.index.DefaultScanner.scan(DefaultScanner.java:60)
	at org.apache.maven.index.DefaultNexusIndexer.scan(DefaultNexusIndexer.java:291)
	... 8 more 
```

Opened a PR here with a fix here: https://github.com/apache/maven-indexer/pull/225

---

**Affects:** 6.2.1

**Remote Links:**
- [GitHub Pull Request #225
](https://github.com/apache/maven-indexer/pull/225)

**Comment by jira-importer** [comment]
**[Fabian Windheuser](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER285178)** commented

I also wonder if we want to have this check in the getSnapshotGav#M2GavCalculator method:

https://github.com/apache/maven-indexer/blob/4f17e8e6304e0ff605f0e366992918dbce1227b6/indexer-core/src/main/java/org/apache/maven/index/artifact/M2GavCalculator.java#L124-L129

Currently, the exception will appear again as soon as a new "metadata" file appears that we did not account for. We probably want to be a bit defensive here and only try to parse the artifact if it matches the expected format? Happy to add this as a follow-up PR if desired!

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Frankly, maven-indexer was NEVER intended to scan LOCAL REPOSITORY, it was envisioned to scan REMOTE REPOSITORY (as you see, there are some slight differences between two). But, scanning local repositories today seems just as valid use case.
As a future remark, we may want to externalize scanning completely, and have indexer just be "fed" with discovered files?

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Merged to
* master
* maven-indexer-6.2.x
