### ISSUE TITLE
[MINDEXER-84] IllegalArgumentException: docID must be >= 0 and < maxDoc=6954 (got docID=6954)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-indexer#561]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** opened **[MINDEXER-84](https://issues.apache.org/jira/browse/MINDEXER-84?redirect=false)** and commented

Issue reported as
https://issues.sonatype.org/browse/NEXUS-5619

```
java.lang.IllegalArgumentException: docID must be >= 0 and < maxDoc=6954 (got docID=6954)
at org.apache.lucene.index.IndexReader.document(IndexReader.java:1136)
at org.apache.maven.index.updater.IndexDataWriter.writeDocuments(IndexDataWriter.java:173)
at org.apache.maven.index.updater.IndexDataWriter.write(IndexDataWriter.java:93)
at org.apache.maven.index.packer.DefaultIndexPacker.writeIndexData(DefaultIndexPacker.java:436)
at org.apache.maven.index.packer.DefaultIndexPacker.packIndex(DefaultIndexPacker.java:137)
at org.sonatype.nexus.index.DefaultIndexerManager.publishRepositoryIndex(DefaultIndexerManager.java:1479)
at org.sonatype.nexus.index.DefaultIndexerManager.access$1000(DefaultIndexerManager.java:186)
at org.sonatype.nexus.index.DefaultIndexerManager$10.run(DefaultIndexerManager.java:1438)
at org.sonatype.nexus.index.DefaultIndexerManager.shared(DefaultIndexerManager.java:2389)
at org.sonatype.nexus.index.DefaultIndexerManager.publishRepositoryIndex(DefaultIndexerManager.java:1432)
at org.sonatype.nexus.index.DefaultIndexerManager.publishAllIndex(DefaultIndexerManager.java:1369)
at org.sonatype.nexus.tasks.PublishIndexesTask.doRun(PublishIndexesTask.java:59)
at org.sonatype.nexus.scheduling.AbstractNexusTask.call(AbstractNexusTask.java:166)
at org.sonatype.scheduling.DefaultScheduledTask.call(DefaultScheduledTask.java:459)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
at java.lang.Thread.run(Thread.java:662)
```

---
No further details from [MINDEXER-84](https://issues.apache.org/jira/browse/MINDEXER-84?redirect=false)

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Problem is that document IDs -- that are valid only in the scope of IndexReader they were got from -- are fed into another, probably changed instance of IndexReader.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Fixed with PR
https://github.com/apache/maven-indexer/pull/5
