### ISSUE TITLE
[MINDEXER-144] IndexOutOfBoundsException during indexing

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-indexer#623]
**[Michael Bien](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbien)** opened **[MINDEXER-144](https://issues.apache.org/jira/browse/MINDEXER-144?redirect=false)** and commented

Hello devs,

I am encountering IOOBEs while trying to index the local repository using the new maven-indexer.

context:

I am currently trying to upgrade indexer-core from 6.0.0 to 6.1.1 (and lucene 5.x to 8.x) of the NetBeans maven support modules (https://github.com/apache/netbeans/pull/3558). Attached is a pom of a test project which triggers the Exception.

All artifacts which caused the exception were snapshot builds, the attached pom works fine if "-SNAPSHOT" is removed from the version element. The same artifacts indexed fine before, while using indexer-6.0 and lucene 5.x.

```java
...
java.lang.IndexOutOfBoundsException: start 51, end 59, length 55 at java.base/java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1802) at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:680) at java.base/java.lang.StringBuilder.append(StringBuilder.java:218) at org.apache.maven.index.artifact.M2GavCalculator.getSnapshotGav(M2GavCalculator.java:187) at org.apache.maven.index.artifact.M2GavCalculator.pathToGav(M2GavCalculator.java:103) at org.apache.maven.index.DefaultArtifactContextProducer.getGavFromPath(DefaultArtifactContextProducer.java:159) at org.apache.maven.index.DefaultArtifactContextProducer.getArtifactContext(DefaultArtifactContextProducer.java:83) at org.netbeans.modules.maven.indexer.CustomArtifactContextProducer.getArtifactContext(CustomArtifactContextProducer.java:40)
... see attachment
```

 

Please let me know if you need more info or think that this is not an issue with maven-indexer.

 

full exception+pom attached

---

**Affects:** 6.1.1

**Attachments:**
- [ex6](https://issues.apache.org/jira/secure/attachment/13040276/ex6) (_3.03 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/13040277/pom.xml) (_8.30 kB_)

**Remote Links:**
- [GitHub Pull Request #198
](https://github.com/apache/maven-indexer/pull/198)
- [GitHub Pull Request #225
](https://github.com/apache/maven-indexer/pull/225)

**Comment by jira-importer** [comment]
**[Michael Bien](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbien)** commented

is DefaultArtifactContextProducer.isIndexable(file) correct? Shouldn't it also filter out maven-metadata-local.xml?

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Would be cool if you can test the PR with your setup, and confirm that fix is okay for you. Thanks!

**Comment by jira-importer** [comment]
**[Michael Bien](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbien)** commented

tested it and I could index my local repository without having to override DefaultArtifactContextProducer::getGavFromPath and filtering the metatdata files out - no Exceptions in the log.

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Cool, thanks for confirmation (btw, newly added UTs did reproduce very same stack trace you provided, so I was pretty much sure is fixed).

To be frank, indexer started as server side lib to index remote repositories, that have no scoped metadata. Hence, scoped local metadata was never filtered out so far, so this is a good fix.

**Comment by jira-importer** [comment]
**[Fabian Windheuser](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER285178)** commented

We are still running into IndexOutOfBoundsException on the latest version (6.2.1). In our case, some of our repos contain "_remote.repository" files that cause a similar exception. I couldn't find great docs on them but apparently, those started getting added by maven for additional metadata on where a dependency was resolved from.

I put up a PR with a fix here: https://github.com/apache/maven-indexer/pull/225. Would appreciate a review on this. Thanks!

Also happy to track this in a separate issue if preferred!

**Comment by jira-importer** [comment]
**[Tamas Cservenak](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cstamas)** commented

Yes, let's add new issue as this one is already closed, and then I can do a dot release

**Comment by jira-importer** [comment]
**[Fabian Windheuser](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER285178)** commented

Sure, opened https://issues.apache.org/jira/browse/MINDEXER-164. Will update the PR accordingly.
